### ISSUE TITLE
Cx-Flow CLI exception occurs "while retrieving project's remote settings, http error 404 NOT_FOUND"  

### ISSUE THREAD

**Issue by mfeferman-cx** [checkmarx-ltd/cx-flow#637]
### Description

While using CxFlow in command-line interface (CLI) mode, it throws an exception, which it apparently recovers from, while retrieving an existing project's remote settings.

### Expected Behavior
 
It is expected that it will retrieve the remote settings without issue or not display an error message if it is not impactful to the process.

### Actual Behavior

It throws an exception and outputs an error message.

### Reproduction

Can reproduce wherever you use this version in CLI mode and it is scanning an already existing project in Checkmarx.
Configured CxFlow yaml file in repo (bitbucket), configured scan task in plan in Bamboo, run plan, experience exception.
Also ran in BitBucket pipeline and the same error occurs.

[JVL-WEB-JOB1-20.log](https://github.com/checkmarx-ltd/cx-flow/files/5931062/JVL-WEB-JOB1-20.log)

### Environment Details

Running in a Bamboo plan, via a script task, on a local install.  Same thing occurs when running in a Bitbucket pipeline in the cloud.

Bamboo v7.2.2
Bitbucket (in the cloud)
Windows 10
CxFlow v1.6.17

**Comment by MithileshPawar** [comment]
Hi @mfeferman-cx , this bug has been fixed and will be available in the next cxflow release (1.6.18 ). Kindly download the new release once it is available and check again.

**Comment by jbrotsos** [comment]
@mfeferman-cx please confirm it has been fixed.

**Comment by mfeferman-cx** [comment]
@jbrotsos and @MithileshPawar - I'm still seeing the issue in v1.6.18 when doing the CxSAST assessment.  Attached is the raw pipeline output from doing both an SCA and SAST scan, as configured in the cx-flow yaml file.
[pipelineLog-11.txt](https://github.com/checkmarx-ltd/cx-flow/files/5999919/pipelineLog-11.txt)

**Comment by jbrotsos** [comment]
@mfeferman-cx confirmed that indeed was fixed - had an authentication issue.
